import path from 'node:path'
import url from 'node:url'

import type { StarlightRouteData } from '@astrojs/starlight/route-data'
import type { docsSchema } from '@astrojs/starlight/schema'
import type { HookParameters } from '@astrojs/starlight/types'
import type { z } from 'astro/zod'
import yaml from 'yaml'

import { isAbsoluteLink, slugifyPath } from './path'

export function parseFrontmatter(frontmatter: string) {
  return yaml.parse(frontmatter) as StarlightFrontmatter
}

export function getFrontmatterNodeValue(frontmatter: StarlightFrontmatter) {
  return yaml.stringify(frontmatter).trim()
}

export function getDocSlug(docsDir: URL, doc: URL) {
  const docPath = path.relative(url.fileURLToPath(docsDir), url.fileURLToPath(doc)).replaceAll('\\', '/')
  const slug = slugifyPath(docPath)

  return slug === 'index' ? '/' : slug.replace(/\/index$/, '')
}

export function getDocLocale(slug: string, starlightConfig: StarlightUserConfig): string | undefined {
  const locales = Object.keys(starlightConfig.locales ?? {})

  if (locales.length === 0) return undefined

  const localeSegment = slug.split('/')[0]

  if (!localeSegment) return undefined

  return locales.find((locale) => locale === localeSegment)
}

export function addPrefixToSidebarConfig(prefix: string, sidebar: SidebarConfigInputItem[]): SidebarConfig {
  return sidebar.map((item) => {
    if (typeof item === 'string') {
      return addPrefixToSlug(prefix, item)
    } else if ('items' in item) {
      return {
        ...item,
        items: addPrefixToSidebarConfig(prefix, item.items),
      }
    } else if (isSidebarLegacyAutoGroup(item)) {
      return addPrefixToLegacyAutogeneratedGroup(prefix, item)
    } else if ('autogenerate' in item) {
      return {
        ...item,
        autogenerate: addPrefixToAutogenerate(prefix, item.autogenerate),
      }
    } else if ('slug' in item) {
      return {
        ...item,
        slug: addPrefixToSlug(prefix, item.slug),
      }
    } else if (isAbsoluteLink(item.link)) {
      return item
    }

    const segments = item.link.split('/')
    segments.splice(/^[./]/.test(item.link) ? 1 : 0, 0, prefix)

    return {
      ...item,
      link: segments.join('/'),
    }
  })
}

function isSidebarLegacyAutoGroup(item: SidebarConfigInputItem): item is SidebarLegacyAutoGroup {
  return typeof item === 'object' && 'autogenerate' in item && 'label' in item
}

function addPrefixToLegacyAutogeneratedGroup(prefix: string, item: SidebarLegacyAutoGroup): SidebarConfigItem {
  const { autogenerate: legacyAutogenerate, ...group } = item
  const autogenerate = addPrefixToAutogenerate(prefix, legacyAutogenerate)

  if (group.collapsed !== undefined && autogenerate.collapsed === undefined) {
    autogenerate.collapsed = group.collapsed
  }

  return {
    ...group,
    items: [{ autogenerate }],
  }
}

function addPrefixToAutogenerate<T extends { directory: string }>(prefix: string, autogenerate: T): T {
  return {
    ...autogenerate,
    directory: path.posix.join(prefix, autogenerate.directory),
  }
}

function addPrefixToSlug(prefix: string, slug: string) {
  if (slug === '' || slug === 'index') return prefix
  return `${prefix}/${slug}`
}

type StarlightFrontmatter = z.input<ReturnType<ReturnType<typeof docsSchema>>> & {
  slug?: string
  hero?: StarlightFrontmatteHero
}

// Just to simplify type checking when updating the frontmatter,
interface StarlightFrontmatteHero {
  image?: {
    file?: string
    dark?: string
    light?: string
  }
}

export type StarlightUserConfig = HookParameters<'config:setup'>['config']
export type StarlightSidebarUserConfig = StarlightUserConfig['sidebar']

type SidebarConfig = NonNullable<StarlightSidebarUserConfig>
type SidebarConfigItem = SidebarConfig[number]
type SidebarAutogenerateConfig = Extract<SidebarConfigItem, { autogenerate: { directory: string } }>['autogenerate']
type SidebarGroupConfig = Extract<SidebarConfigItem, { items: SidebarConfig }>
type SidebarLegacyAutoGroup = Omit<SidebarGroupConfig, 'items'> & { autogenerate: SidebarAutogenerateConfig }
type SidebarConfigInputItem = SidebarConfigItem | SidebarLegacyAutoGroup

export type StarlightSidebar = StarlightRouteData['sidebar']
