import path from 'node:path'
import url from 'node:url'

import type { StarlightRouteData } from '@astrojs/starlight/route-data'
import type { docsSchema } from '@astrojs/starlight/schema'
import type { HookParameters } from '@astrojs/starlight/types'
import type { z } from 'astro/zod'
import yaml from 'yaml'

import { isAbsoluteLink, slugifyPath, stripLeadingAndTrailingSlashes, stripTrailingSlash } from './path'

const frontmatterRegex = /^---\r?\n(?<yaml>.*?)\r?\n---(?:\r?\n|$)/s
const queryOrFragmentRegex = /[?#]/

export function parseFrontmatter(frontmatter: string) {
  return yaml.parse(frontmatter) as StarlightFrontmatter
}

export function getFrontmatterNodeValue(frontmatter: StarlightFrontmatter) {
  return yaml.stringify(frontmatter).trim()
}

export function getDocPath(docsDir: URL, doc: URL) {
  return path.relative(url.fileURLToPath(docsDir), url.fileURLToPath(doc)).replaceAll('\\', '/')
}

export function getDocSlug(docsDir: URL, doc: URL) {
  const slug = slugifyPath(getDocPath(docsDir, doc))

  return slug === 'index' ? '/' : slug.replace(/\/index$/, '')
}

export function resolveDocSlug(docsDir: URL, doc: URL, content: string) {
  const frontmatter = frontmatterRegex.exec(content)?.groups?.['yaml']
  const customSlug = frontmatter ? parseFrontmatter(frontmatter).slug : undefined

  return stripLeadingAndTrailingSlashes(typeof customSlug === 'string' ? customSlug : getDocSlug(docsDir, doc))
}

// https://github.com/withastro/starlight/blob/ff5090a8fd7ae068b29e3c5af7197c5e5afdfa4e/packages/starlight/utils/slugs.ts#L104
export function getURLSlug(url: URL) {
  let pathname = decodeURI(url.pathname)

  const base = stripTrailingSlash(import.meta.env.BASE_URL)
  if (pathname.startsWith(base)) pathname = pathname.replace(base, '')

  const segments = pathname.split('/')
  const htmlExt = '.html'

  if (segments.at(-1) === 'index.html') {
    // Remove trailing `index.html`.
    segments.pop()
  } else if (segments.at(-1)?.endsWith(htmlExt)) {
    // Remove trailing `.html`.
    const last = segments.pop()
    if (last) segments.push(last.slice(0, -1 * htmlExt.length))
  }

  return segments.filter(Boolean).join('/')
}

export function getDocLocale(slug: string, starlightConfig: StarlightUserConfig): string | undefined {
  const locales = Object.keys(starlightConfig.locales ?? {})

  if (locales.length === 0) return undefined

  const localeSegment = slug.split('/')[0]

  if (!localeSegment) return undefined

  return locales.find((locale) => locale === localeSegment)
}

export function getSidebarLinks(sidebar: StarlightSidebar): Extract<StarlightSidebar[number], { type: 'link' }>[] {
  return sidebar.flatMap((entry) => (entry.type === 'group' ? getSidebarLinks(entry.entries) : entry))
}

export function addPrefixToSidebarConfig(
  prefix: string,
  sidebar: SidebarConfigInputItem[],
  excludedSlugs: string[] = [],
): SidebarConfig {
  return sidebar.map((item) => {
    if (typeof item === 'string') {
      return isExcludedInternalSidebarSlug(item, excludedSlugs) ? item : addPrefixToSlug(prefix, item)
    } else if ('items' in item) {
      return {
        ...item,
        items: addPrefixToSidebarConfig(prefix, item.items, excludedSlugs),
      }
    } else if (isSidebarLegacyAutoGroup(item)) {
      return addPrefixToLegacyAutogeneratedGroup(prefix, item)
    } else if ('autogenerate' in item) {
      return {
        ...item,
        autogenerate: addPrefixToAutogenerate(prefix, item.autogenerate),
      }
    } else if ('slug' in item) {
      return {
        ...item,
        slug: isExcludedInternalSidebarSlug(item.slug, excludedSlugs) ? item.slug : addPrefixToSlug(prefix, item.slug),
      }
    } else if (isAbsoluteLink(item.link)) {
      return item
    }

    const link = item.link.startsWith('./') ? item.link.slice(2) : item.link
    if (isExcludedSidebarSlug(link, excludedSlugs)) return item

    const segments = item.link.split('/')
    segments.splice(/^[./]/.test(item.link) ? 1 : 0, 0, prefix)

    return {
      ...item,
      link: segments.join('/'),
    }
  })
}

function isExcludedSidebarSlug(value: string, excludedSlugs: string[]) {
  const pathname = value.split(queryOrFragmentRegex)[0] ?? ''
  const slug = stripLeadingAndTrailingSlashes(pathname)
  return excludedSlugs.includes(slug)
}

function isExcludedInternalSidebarSlug(slug: string, excludedSlugs: string[]) {
  return isExcludedSidebarSlug(slug === 'index' ? '' : slug, excludedSlugs)
}

function isSidebarLegacyAutoGroup(item: SidebarConfigInputItem): item is SidebarLegacyAutoGroup {
  return typeof item === 'object' && 'autogenerate' in item && 'label' in item
}

function addPrefixToLegacyAutogeneratedGroup(prefix: string, item: SidebarLegacyAutoGroup): SidebarConfigItem {
  const { autogenerate: legacyAutogenerate, ...group } = item
  const autogenerate = addPrefixToAutogenerate(prefix, legacyAutogenerate)

  if (group.collapsed !== undefined && autogenerate.collapsed === undefined) {
    autogenerate.collapsed = group.collapsed
  }

  return {
    ...group,
    items: [{ autogenerate }],
  }
}

function addPrefixToAutogenerate<T extends { directory: string }>(prefix: string, autogenerate: T): T {
  return {
    ...autogenerate,
    directory: path.posix.join(prefix, autogenerate.directory),
  }
}

function addPrefixToSlug(prefix: string, slug: string) {
  if (slug === '' || slug === 'index') return prefix
  return `${prefix}/${slug}`
}

type StarlightFrontmatter = z.input<ReturnType<ReturnType<typeof docsSchema>>> & {
  slug?: string
  hero?: StarlightFrontmatteHero
}

// Just to simplify type checking when updating the frontmatter,
interface StarlightFrontmatteHero {
  image?: {
    file?: string
    dark?: string
    light?: string
  }
}

export type StarlightUserConfig = HookParameters<'config:setup'>['config']
export type StarlightSidebarUserConfig = StarlightUserConfig['sidebar']

type SidebarConfig = NonNullable<StarlightSidebarUserConfig>
type SidebarConfigItem = SidebarConfig[number]
type SidebarAutogenerateConfig = Extract<SidebarConfigItem, { autogenerate: { directory: string } }>['autogenerate']
type SidebarGroupConfig = Extract<SidebarConfigItem, { items: SidebarConfig }>
type SidebarLegacyAutoGroup = Omit<SidebarGroupConfig, 'items'> & { autogenerate: SidebarAutogenerateConfig }
type SidebarConfigInputItem = SidebarConfigItem | SidebarLegacyAutoGroup

export type StarlightSidebar = StarlightRouteData['sidebar']
