import { describe, expect, test } from 'vitest'

import { addPrefixToSidebarConfig, getDocSlug } from '../libs/starlight'

describe('getDocSlug', () => {
  const docsDir = new URL('content/docs/', import.meta.url)

  test('handles root index file', () => {
    expect(getDocSlug(docsDir, new URL('index.md', docsDir))).toBe('/')
  })

  test('handles nested index files', () => {
    expect(getDocSlug(docsDir, new URL('guides/index.md', docsDir))).toBe('guides')
  })

  test('handles root files', () => {
    expect(getDocSlug(docsDir, new URL('test.mdx', docsDir))).toBe('test')
  })

  test('handles nested files', () => {
    expect(getDocSlug(docsDir, new URL('guides/examples/test.mdx', docsDir))).toBe('guides/examples/test')
  })
})

describe('addPrefixToSidebarConfig', () => {
  test('does not prefix absolute links', () => {
    expect(addPrefixToSidebarConfig('5.0', [{ label: 'Test', link: 'https://starlight.astro.build' }]))
      .toMatchInlineSnapshot(`
      [
        {
          "label": "Test",
          "link": "https://starlight.astro.build",
        },
      ]
    `)
  })

  test('prefix links to the home page', () => {
    expect(addPrefixToSidebarConfig('4.0', ['', 'index'])).toMatchInlineSnapshot(`
      [
        "4.0",
        "4.0",
      ]
    `)
  })

  test('prefix root links', () => {
    expect(
      addPrefixToSidebarConfig('3.0', [
        { label: 'Test 1', link: '/test-1/' },
        { label: 'Test 2', link: './test-2/' },
        { label: 'Test 3', link: '/' },
      ]),
    ).toMatchInlineSnapshot(`
      [
        {
          "label": "Test 1",
          "link": "/3.0/test-1/",
        },
        {
          "label": "Test 2",
          "link": "./3.0/test-2/",
        },
        {
          "label": "Test 3",
          "link": "/3.0/",
        },
      ]
    `)
  })

  test('prefix links in groups', () => {
    expect(
      addPrefixToSidebarConfig('3.0', [
        {
          label: 'Group',
          items: [
            { label: 'Test 1', link: '/group/test-1/' },
            { label: 'Test 2', link: './group/test-2/' },
          ],
        },
      ]),
    ).toMatchInlineSnapshot(`
      [
        {
          "items": [
            {
              "label": "Test 1",
              "link": "/3.0/group/test-1/",
            },
            {
              "label": "Test 2",
              "link": "./3.0/group/test-2/",
            },
          ],
          "label": "Group",
        },
      ]
    `)
  })

  test('prefix autogenerated groups', () => {
    expect(
      addPrefixToSidebarConfig('2.0', [
        {
          label: 'Group',
          autogenerate: { directory: 'test' },
        },
      ]),
    ).toMatchInlineSnapshot(`
      [
        {
          "autogenerate": {
            "directory": "2.0/test",
          },
          "label": "Group",
        },
      ]
    `)
  })

  test('prefix links in groups', () => {
    expect(
      addPrefixToSidebarConfig('3.0', [
        { slug: 'test-root-1' },
        'test-root-2',
        {
          label: 'Group',
          items: [
            { label: 'Test 1', slug: 'group/test-nested-1' },
            { slug: 'group/test-nested-2' },
            'group/test-nested-3',
          ],
        },
      ]),
    ).toMatchInlineSnapshot(`
      [
        {
          "slug": "3.0/test-root-1",
        },
        "3.0/test-root-2",
        {
          "items": [
            {
              "label": "Test 1",
              "slug": "3.0/group/test-nested-1",
            },
            {
              "slug": "3.0/group/test-nested-2",
            },
            "3.0/group/test-nested-3",
          ],
          "label": "Group",
        },
      ]
    `)
  })
})
